const stageNames=['Vermutung','Garten erkunden','Aussagen prüfen','Begriffe','Transfer'];
const key='lernweg-meisen-v2';
const defaultState={stage:0,done:[],found:[],terms:{},finalText:''};
let state={...defaultState,...JSON.parse(localStorage.getItem(key)||'{}')};
const stages=[...document.querySelectorAll('.stage')];
const nav=document.querySelector('#stepNav');
const info={
 great:{title:'Kohlmeise',tag:'Körperbau und Raum',text:'Die Kohlmeise ist größer und schwerer. Sie sucht häufig an kräftigen, inneren Ästen und teilweise am Boden nach Nahrung.'},
 blue:{title:'Blaumeise',tag:'Körperbau und Raum',text:'Die kleinere, leichtere Blaumeise erreicht dünne äußere Zweige und Blätter besonders gut.'},
 caterpillar:{title:'Größere Beutetiere',tag:'Nahrung',text:'Kohlmeisen nutzen neben kleinen Gliederfüßern auch größere Insektenlarven und im Winter häufig Samen.'},
 leaves:{title:'Kleine Gliederfüßer',tag:'Nahrung',text:'Blaumeisen lesen häufig kleine Insekten, Spinnen und andere Gliederfüßer von Blättern und feinen Zweigen ab.'},
 largeBox:{title:'Größere Höhlenöffnung',tag:'Nistplatz',text:'Eine runde Öffnung von etwa 32 mm ist für Kohlmeisen geeignet. Auch kleinere Meisen können grundsätzlich große Öffnungen nutzen – dort kann Konkurrenz entstehen.'},
 smallBox:{title:'Kleine Höhlenöffnung',tag:'Nistplatz',text:'Durch Öffnungen von etwa 26–28 mm passt die Blaumeise, die größere Kohlmeise jedoch nicht. Die kleine Öffnung verändert damit den Zugang zur Ressource Nistplatz.'},
 feeder:{title:'Gemeinsame Futterquelle',tag:'Nischenüberlappung',text:'Am Futterhaus nutzen beide Arten beispielsweise Sonnenblumenkerne. Ihre Nahrungsspektren überlappen sich also.'},
 ground:{title:'Boden und Laubstreu',tag:'Raumnutzung',text:'Die Kohlmeise sucht häufiger als die Blaumeise auch an kräftigen Strukturen und am Boden. Die Blaumeise meidet den Boden nicht vollständig, nutzt aber typischerweise stärker die äußere Baumkrone.'}
};
function save(){localStorage.setItem(key,JSON.stringify(state))}
function setDone(i){if(!state.done.includes(i))state.done.push(i);save();renderNav()}
function renderNav(){nav.innerHTML='';stageNames.forEach((name,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.className=i===state.stage?'current':'';b.innerHTML=`<span class="step-number">${i+1}</span><span class="step-name">${name}</span><span class="step-done">${state.done.includes(i)?'✓':''}</span>`;b.onclick=()=>showStage(i);li.append(b);nav.append(li)});document.querySelector('#progressText').textContent=`${state.done.length} von 5`;document.querySelector('#progressFill').style.width=`${state.done.length/5*100}%`}
function showStage(i){state.stage=Math.max(0,Math.min(stages.length-1,i));stages.forEach((s,j)=>s.classList.toggle('active',j===state.stage));save();renderNav();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.next').forEach(b=>b.onclick=()=>{if(state.stage===0)setDone(0);showStage(state.stage+1)});document.querySelectorAll('.prev').forEach(b=>b.onclick=()=>showStage(state.stage-1));
function feedback(el,ok,good,bad){el.textContent=ok?good:bad;el.className=`feedback show ${ok?'good':'try'}`}
document.querySelectorAll('.hotspot').forEach(b=>{if(state.found.includes(b.dataset.hotspot))b.classList.add('found');b.onclick=()=>{const id=b.dataset.hotspot,d=info[id];if(!state.found.includes(id))state.found.push(id);b.classList.add('found');document.querySelector('#evidenceTitle').textContent=d.title;document.querySelector('#evidenceText').textContent=d.text;document.querySelector('#evidenceTag').textContent=d.tag;renderEvidence();if(state.found.length===Object.keys(info).length)setDone(1);save()}});
function renderEvidence(){document.querySelector('#hotspotCount').textContent=`${state.found.length} von 8 Informationen gefunden`;const log=document.querySelector('#evidenceLog');log.innerHTML='';state.found.forEach(id=>{const b=document.createElement('button');b.type='button';b.className='evidence-chip';b.textContent=info[id].title;b.onclick=()=>{document.querySelector(`.hotspot[data-hotspot="${id}"]`).click()};log.append(b)})}renderEvidence();
document.querySelector('#hintToggle').onclick=e=>{const on=document.querySelector('#scene').classList.toggle('show-hints');e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Suchbereiche ausblenden':'Suchbereiche kurz zeigen'};
document.querySelector('#checkClaims').onclick=()=>{const picked=[...document.querySelectorAll('[data-stage="2"] .claim-set input:checked')].map(x=>x.value),need=['sameHabitat','reduce','coexist'],ok=need.every(x=>picked.includes(x))&&picked.length===need.length;feedback(document.querySelector('#claimFeedback'),ok,'Richtig: Beide Arten teilen einen Lebensraum. Unterschiede in der Ressourcennutzung können ihre Konkurrenz verringern und die Koexistenz begünstigen.','Drei Aussagen sind fachlich richtig. Unterscheide zwischen einem Körpermerkmal und der gesamten ökologischen Nische; ähnliche Ansprüche bedeuten außerdem nicht automatisch identische Nischen.');document.querySelector('#patternStrip').hidden=!ok;if(ok)setDone(2)};
document.querySelectorAll('[data-term]').forEach(s=>{s.value=state.terms?.[s.dataset.term]||'';s.onchange=()=>{state.terms[s.dataset.term]=s.value;s.classList.remove('correct','wrong');save()}});
document.querySelector('#checkTerms').onclick=()=>{let correct=0;document.querySelectorAll('[data-term]').forEach(s=>{const ok=s.value===s.dataset.term;s.classList.toggle('correct',ok);s.classList.toggle('wrong',!ok);if(ok)correct++});const ok=correct===4;feedback(document.querySelector('#termFeedback'),ok,'Alle vier Zuordnungen sind richtig. Lebensraum, Nischenüberlappung, Nischendifferenzierung und ökologische Nische sind voneinander abgegrenzt.',`${correct} von 4 Zuordnungen sind richtig. Prüfe besonders den Unterschied zwischen dem Ort, den teilweise gleichen Ansprüchen und der gesamten Nische.`);if(ok)setDone(3)};
document.querySelector('#checkTransfer').onclick=()=>{const box=[...document.querySelectorAll('[data-stage="4"] .claim-set input:checked')].map(x=>x.value),need=['blueLoss','nestCompetition','diversity'],ok=need.every(x=>box.includes(x))&&box.length===need.length;feedback(document.querySelector('#transferFeedback'),ok,'Plausible Prognose: Weniger Strukturvielfalt reduziert Ausweichmöglichkeiten und kann Konkurrenz verstärken.','Drei Folgen sind plausibel. Wenn beide Arten dieselbe Nistkastenöffnung nutzen können, nimmt die Überlappung bei dieser Ressource eher zu. Stärkere Konkurrenz führt außerdem nicht zwangsläufig zur Verdrängung.');if(ok)setDone(4)};
const finalText=document.querySelector('#finalText');finalText.value=state.finalText||'';finalText.oninput=()=>{state.finalText=finalText.value;save()};document.querySelector('#showModel').onclick=()=>document.querySelector('#modelAnswer').hidden=!document.querySelector('#modelAnswer').hidden;
document.querySelector('#finishBtn').onclick=()=>{if(state.finalText.trim().length<50){feedback(document.querySelector('#transferFeedback'),false,'','Erläutere zuerst begründet, wie sich die Konkurrenz in dem Szenario verändert.');return}setDone(4);document.querySelector('#completion').classList.add('show')};
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Möchtest du alle Eingaben und den Lernfortschritt löschen?')){localStorage.removeItem(key);location.reload()}};
renderNav();showStage(state.stage);
